/* Split data/questions.js (all 2407 questions, 720KB gzip) into
     data/questions.js       — Class B only (1262), what a B learner actually needs
     data/questions-more.js  — the other 1145 (trucks/buses/…), fetched only when
                               the learner flips the scope switch to "all"
   Run from the repo root:  node work/split-catalog.mjs
   Reads the *existing* data/questions.js, so it is re-runnable after a catalog update. */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const full = path.join(root, "data/questions.js");
const src = fs.readFileSync(full, "utf8");
const json = src.slice(src.indexOf("["), src.lastIndexOf("]") + 1);
const all = JSON.parse(json);

const isB = (q) => {
  const m = /^([0-9.]+)-(\d+)/.exec(q.id);
  if (!m) return true;
  return m[1].charAt(0) === "1" || m[2].charAt(0) === "1";
};

const b = all.filter(isB);
const more = all.filter((q) => !isB(q));
if (b.length + more.length !== all.length) throw new Error("split lost questions");

const HEAD_B = `/* German driving-theory catalog (official Fragenkatalog) — Class B subset.
   Every question a Klasse B learner can be asked (Teil 1 + Zusatzstoff 1xx).
   The other ${more.length} questions (trucks/buses/…) live in data/questions-more.js and are
   fetched only when the scope switch is set to "all" — see app.js ensureAllQ().
   Includes the sentence stem for completion-type questions (field "s" English / "sd" German). */
`;
const HEAD_MORE = `/* German driving-theory catalog — the non-Class-B questions (${more.length}).
   Loaded on demand by app.js ensureAllQ() when the learner switches scope to "all".
   Generated by work/split-catalog.mjs — do not hand-edit. */
`;

fs.writeFileSync(full, HEAD_B + "window.__CATALOG = " + JSON.stringify(b) + ";\n" +
  "window.__CATALOG_ALL_COUNT = " + all.length + ";\n");
fs.writeFileSync(path.join(root, "data/questions-more.js"),
  HEAD_MORE + "window.__CATALOG_MORE = " + JSON.stringify(more) + ";\n");

console.log("class B:", b.length, "· other:", more.length, "· total:", all.length);
