/* Split i18n.js (10 UI language packs, 68KB gzip) so that English — the default and
   the fallback — is all a first-time visitor downloads:
     i18n.js       — window.I18N = { en: … }        (always loaded, ~6.5KB gzip)
     i18n-more.js  — window.I18N_MORE = { zh, de, ru, tr, uk, pl, ro, vi, ar }
                     fetched by app.js ensureI18n() when the site language is not English
   Idempotent: reads the union of both files, so re-running is safe.
   Run from the repo root:  node work/split-i18n.mjs */
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const root = path.resolve(import.meta.dirname, "..");
const main = path.join(root, "i18n.js");
const more = path.join(root, "i18n-more.js");

const ctx = { window: {} };
vm.runInNewContext(fs.readFileSync(main, "utf8"), ctx);
if (fs.existsSync(more)) vm.runInNewContext(fs.readFileSync(more, "utf8"), ctx);
const all = Object.assign({}, ctx.window.I18N_MORE, ctx.window.I18N);
if (!all.en) throw new Error("no English pack found");

const rest = Object.keys(all).filter((k) => k !== "en");
const order = ["zh", "de", "ru", "tr", "uk", "pl", "ro", "vi", "ar"].filter((k) => rest.includes(k));
for (const k of rest) if (!order.includes(k)) order.push(k);

const HEAD = `/* i18n.js — UI strings. en is hand-written and is also the fallback every other pack
   resolves against, so it ships in the first payload. The other ${order.length} packs live in
   i18n-more.js and are fetched by app.js ensureI18n() only when the site language needs one. */
`;
const HEAD_MORE = `/* i18n-more.js — the non-English UI packs (${order.join(", ")}).
   Loaded on demand by app.js ensureI18n(). Generated by work/split-i18n.mjs — do not hand-edit. */
`;

fs.writeFileSync(main, HEAD + "window.I18N = {\n  en: " + JSON.stringify(all.en, null, 2).replace(/\n/g, "\n  ") + ",\n};\n");
fs.writeFileSync(more, HEAD_MORE + "window.I18N_MORE = {\n" +
  order.map((k) => "  " + k + ": " + JSON.stringify(all[k], null, 2).replace(/\n/g, "\n  ") + ",").join("\n") +
  "\n};\n");

console.log("en keys:", Object.keys(all.en).length, "· more:", order.join(","));
